### ISSUE TITLE
TSL2591 overflows under direct sunlight despite GAIN_LOW INTEGRATIONTIME_100MS options set

### ISSUE THREAD

**Issue by averter** [adafruit/Adafruit_CircuitPython_TSL2591#27]
The error message discussed [here](https://github.com/adafruit/Adafruit_CircuitPython_TSL2591/issues/20) is helpful, but my tsl2591 is under direct sunlight with `GAIN_LOW` and `INTEGRATIONTIME_100MS` and the code keeps crashing... With this configuration isn't this sensor supposed to work even under these extreme light conditions? I'm copying my code below for reference.

````python
import board
import adafruit_tsl2591
import time
import requests
i2c = board.I2C()
sensor = adafruit_tsl2591.TSL2591(i2c)
sensor.gain = adafruit_tsl2591.GAIN_LOW
sensor.integration_time = adafruit_tsl2591.INTEGRATIONTIME_100MS
READING_DELAY = 1
time.sleep(READING_DELAY)
print(sensor.lux)
````

**Comment by lamasek** [comment]
Maybe i have 1 anothe answer. Typical maximum summer dayligt in Europe Czech Republic is around 100 000 LUX. TSL 2591 has specified maximum 88 000 LUX. Also 100 000 LUX is roughly 1 cm far from 100W classic light bulb.
For measuring outside i bought another LUX meter chip, but now i am trying this if it is more precise.

**Comment by averter** [comment]
That makes sense. Perhaps this sensor it's not the best for an application with direct sunlight? Is there any way to double check that this is the source of error?

**Comment by averter** [comment]
- I'll assume that this is indeed due to the limited range of the sensor. An alternative would be this [SEN0390](https://www.dfrobot.com/product-2183.html) sensor with a range of up to 200k lux, although there seems to only exist libraries for arduino (not the rpi).
